=== Danysan1/osm-wikidata-map-framework/front-end/src/generated/preset.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "background_color": {
            "description": "Background color for controls and popups",
            "type": "string"
        },
        "feature_filter_classes": {
            "description": "Whitelist of Q-IDs of Wikidata classes to consider when filtering features from Wikidata",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "fetch_parts_of_linked_entities": {
            "description": "Whether to fetch parts of linked entities (e.g. the members of a duo)",
            "type": "boolean"
        },
        "id": {
            "description": "Unique identifier for the source preset.",
            "type": "string"
        },
        "ignore_big_elements": {
            "description": "When using Overpass-based back-ends, big elements like country/region borders and the biggest lakes can create major slowdowns.\nTo display them pmtiles-based back-ends are recommended.\nThis setting allows to filter out big elements in the Overpass queries used by Overpass-based back-ends.",
            "type": "boolean"
        },
        "linked_entity_filter_classes": {
            "description": "Whitelist of Q-IDs of Wikidata classes to consider when filtering linked entities",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "mapcomplete_theme": {
            "description": "ID of the MapComplete theme to link to from the button in the feature details popup",
            "type": "string"
        },
        "osm_description_key": {
            "description": "OSM key whose value contains the description of the linked entity",
            "type": "string"
        },
        "osm_filter_tags": {
            "description": "OSM tags to use for filtering the results.\nFor optimal performance if you initialize the DB from OSM PBF dump sort the tags from the most frequent to the least frequent.",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "osm_text_key": {
            "description": "OSM key whose value contains the human readable name of the linked entity",
            "type": "string"
        },
        "osm_wikidata_keys": {
            "description": "OSM keys which connect the subject (map element) to the linked entity (popup element)",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "osm_wikidata_properties": {
            "description": "P-IDs of the Wikidata properties which connect the subject (map element) to the linked entity (popup element)",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "relation_member_role": {
            "description": "OSM relation role to consider when using an OSM relation as linked entity",
            "type": "string"
        },
        "relation_propagation_role": {
            "description": "OSM relation member role to consider when propagating linked entities from relations to their members",
            "type": "string"
        },
        "relation_propagation_type": {
            "description": "OSM relation type to consider when propagating linked entities from relations to their members",
            "type": "string"
        },
        "require_wikidata_link": {
            "description": "Whether all OSM elements, even in presets without linked entities, should have either a direct or secondary wikidata link.\nIn practice this means that only OSM elements with wikidata=* or *:wikidata=* will be fetched.",
            "type": "boolean"
        },
        "use_linked_entity_count": {
            "description": "Whether to show linked entity count (instead of feature count) in clusters",
            "type": "boolean"
        },
        "use_min_zoom_level": {
            "description": "Whether to use the min_zoom_level setting",
            "type": "boolean"
        },
        "wikidata_image_property": {
            "description": "P-ID of the Wikidata property which connects the linked entity (popup element) to a Wikimedia Commons image of the subject (map element)",
            "type": "string"
        },
        "wikidata_indirect_property": {
            "description": "P-ID of the Wikidata property which connects the linked entity (popup element) to a relation whose P625 qualifier identifies the coordinates of the subject (map element)",
            "type": "string"
        }
    },
    "type": "object"
}

=== Danysan1/osm-wikidata-map-framework/front-end/public/presets/network.json
{
  "background_color": "hsl(210, 100%, 96%)",
  "ignore_big_elements": true,
  "mapcomplete_theme": "transit",
  "osm_filter_tags": [
    "network:wikidata",
    "network",
    "public_transport"
  ],
  "osm_text_key": "network",
  "osm_wikidata_keys": [
    "network:wikidata"
  ],
  "osm_wikidata_properties": [
    "P16"
  ],
  "require_wikidata_link": true,
  "use_min_zoom_level": true
}

=== Danysan1/osm-wikidata-map-framework/front-end/public/presets/aircraft.json
{
    "background_color": "hsl(180, 100%, 96%)",
    "osm_filter_tags": [
        "artwork_type=aircraft",
        "historic=aircraft",
        "historic=aircraft_wreck",
        "memorial=aircraft"
    ],
    "osm_text_key": "model",
    "osm_wikidata_keys": [
        "model:wikidata"
    ],
    "osm_wikidata_properties": [
        "P31"
    ],
    "linked_entity_filter_classes": [
        "Q45296117",
        "Q15056995",
        "Q15056993",
        "Q111722634",
        "Q110055303"
    ],
    "require_wikidata_link": false
}

=== Danysan1/osm-wikidata-map-framework/front-end/public/presets/model.json
{
    "background_color": "hsl(180, 100%, 96%)",
    "osm_text_key": "model",
    "osm_wikidata_keys": [
        "model:wikidata"
    ],
    "osm_wikidata_properties": [
        "P31"
    ],
    "require_wikidata_link": true,
    "linked_entity_filter_classes": [
        "Q19832486",
        "Q45296117",
        "Q15056995",
        "Q15056993",
        "Q111722634",
        "Q110055303"
    ]
}

=== Danysan1/osm-wikidata-map-framework/front-end/public/presets/species.json
{
    "background_color": "hsl(150, 100%, 96%)",
    "fetch_parts_of_linked_entities": true,
    "mapcomplete_theme": "trees",
    "osm_text_key": "species",
    "osm_wikidata_keys": [
        "species:wikidata"
    ],
    "osm_wikidata_properties": [
        "P10241"
    ],
    "require_wikidata_link": true,
    "use_min_zoom_level": true
}

=== Danysan1/osm-wikidata-map-framework/front-end/public/presets/artist.json
{
    "background_color": "hsl(30, 100%, 96%)",
    "fetch_parts_of_linked_entities": true,
    "mapcomplete_theme": "artwork",
    "osm_filter_tags": [
        "artist:wikidata",
        "artist_name",
        "tourism",
        "historic",
        "amenity=fountain"
    ],
    "osm_text_key": "artist_name",
    "osm_wikidata_keys": [
        "artist:wikidata"
    ],
    "osm_wikidata_properties": [
        "P170",
        "P50"
    ],
    "require_wikidata_link": true
}

=== Danysan1/osm-wikidata-map-framework/front-end/public/presets/burial.json
{
  "background_color": "hsl(0, 0%, 96%)",
  "fetch_parts_of_linked_entities": true,
  "osm_filter_tags": [
    "buried:wikidata",
    "buried",
    "historic=tomb",
    "tomb",
    "cemetery",
    "landuse=cemetery",
    "amenity=place_of_worship",
    "amenity=grave_yard"
  ],
  "osm_text_key": "buried",
  "osm_description_key": "buried:description",
  "osm_wikidata_keys": [
    "buried:wikidata",
    "subject:wikidata"
  ],
  "relation_member_role": "tomb",
  "wikidata_indirect_property": "P119",
  "wikidata_image_property": "P1442",
  "use_linked_entity_count": true,
  "require_wikidata_link": true,
  "use_min_zoom_level": true
}

=== Danysan1/osm-wikidata-map-framework/front-end/public/presets/brand.json
{
  "background_color": "hsl(60, 100%, 96%)",
  "mapcomplete_theme": "shops",
  "osm_filter_tags": [
    "brand:wikidata",
    "brand",
    "shop",
    "amenity"
  ],
  "osm_text_key": "brand",
  "osm_wikidata_keys": [
    "brand:wikidata"
  ],
  "osm_wikidata_properties": [
    "P1716"
  ],
  "require_wikidata_link": true,
  "use_min_zoom_level": true
}

=== Danysan1/osm-wikidata-map-framework/front-end/public/presets/etymology.json
{
  "background_color": "hsl(90, 100%, 96%)",
  "fetch_parts_of_linked_entities": true,
  "ignore_big_elements": true,
  "mapcomplete_theme": "etymology",
  "osm_filter_tags": [
    "name:etymology:wikidata",
    "name:etymology",
    "name=*"
  ],
  "osm_text_key": "name:etymology",
  "osm_description_key": "name:etymology:description",
  "osm_wikidata_keys": [
    "name:etymology:wikidata",
    "subject:wikidata"
  ],
  "osm_wikidata_properties": [
    "P138",
    "P825",
    "P547"
  ],
  "relation_propagation_role": "street",
  "require_wikidata_link": true,
  "use_min_zoom_level": true
}
